apiVersion: v1
data:
  dex.config: |-
    logger:
      level: debug
    connectors:
    - type: ldap
      name: contoso.lan
      id: ldap
      config:
        # Ldap server address
        host: "10.11.12.19:389"
        insecureNoSSL: true
        insecureSkipVerify: true
        # Variable name stores ldap bindDN in argocd-secret
        bindDN: "administrator@contoso.lan"
        # Variable name stores ldap bind password in argocd-secret
        bindPW: "123abc."
        usernamePrompt: Username # Customizable prompt for argocd dex login
        # Ldap user search attributes
        userSearch:
          baseDN: "OU=USERS,OU=ARGOCD,DC=contoso,DC=lan"
          filter: "(objectClass=user)"
          username: cn
          idAttr: cn
          emailAttr: cn
          nameAttr: cn
        # Ldap group serch attributes
        groupSearch:
          baseDN: "OU=GROUPS,OU=ARGOCD,DC=contoso,DC=lan"
          filter: "(objectClass=group)"
          userAttr: dn
          groupAttr: member
          nameAttr: cn
  url: https://localhost:8080
  admin.enabled: "false"
  server.rbac.log.enforce.enable: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
