apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.default: role:none
  scopes: '[groups, uid]'
  policy.csv: |
    p, role:none, *, *, */*, deny
    g, GP_ARGOCD_ADMIN, role:admin